F1 =int(input("Enter Fruit Name 1:"))
F2 =int(input("Enter Fruit Name 2:"))
F3 =int(input("Enter Fruit Name 3:"))
F4 =int(input("Enter Fruit Name 4:"))
F5 =int(input("Enter Fruit Name 5:"))
F6 =int(input("Enter Fruit Name 6:"))
F7 =int(input("Enter Fruit Name 7:"))
Marklist = [F1, F2, F3, F4 , F5, F6, F7]
Marklist.sort()
print (Marklist)